### ISSUE TITLE
Error with Rigel's RoboMaker Plugin

### ISSUE THREAD

**Issue by Kazadhum** [Kazadhum/atom#7] opened 2023-07-19 10:46 UTC
Hi @MisterOwlPT! 

I've got some doubts as to how to use the RoboMaker plugin for Rigel. 

1. The template I have for the Rigelfile is from way back when I started working with Rigel. Having gone through many updates, is there anything I should know about that has changed?

2. In order to only run one container (in this case, only the robot-app), so I simply not include the other one?

Besides these questions, I've tried using the plugin a couple of times and I've ran into an traceback message that I don't understand (I've removed the ECR link from the message):

```
WARNING - Press CTRL-C / CTRL-Z to stop execution
Connecting to providers
Attempting login with ECR '********************************'

Login Succeeded
Logged in with success to ECR '********************************'
Authenticated with AWS RoboMaker.
Found existing robot application 'rigel_robomaker_robot_application'
Traceback (most recent call last):
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/bin/rigel", line 6, in <module>
    sys.exit(main())
  File "/home/diogo/rigel/rigel/main.py", line 50, in main
    cli()
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/diogo/rigel/rigel/cli/command.py", line 23, in callback
    f(self, *f_args, **f_kwargs)
  File "/home/diogo/rigel/rigel/cli/run.py", line 25, in job
    orchestrator.run_job(job)
  File "/home/diogo/rigel/rigel/orchestrator.py", line 222, in run_job
    self.execute(execution_plan)
  File "/home/diogo/rigel/rigel/orchestrator.py", line 199, in execute
    stage.execute(
  File "/home/diogo/rigel/rigel/executor.py", line 218, in execute
    job.setup()
  File "/home/diogo/rigel/rigel/plugins/aws/robomaker/plugin.py", line 257, in setup
    self.__simulation_job = self.create_simulation_job()
  File "/home/diogo/rigel/rigel/plugins/aws/robomaker/plugin.py", line 192, in create_simulation_job
    simulation_job = self.__robomaker_client.create_simulation_job(**kwargs)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/botocore/client.py", line 919, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid length for parameter dataSources, value: 0, valid min length: 1
```

For reference, here's the Rigelfile section regarding the RoboMaker plugin:

```
robomaker:
    plugin: "rigel.plugins.aws.RoboMakerPlugin"
    with:
      iam_role: "{{ vars.AWS_IAM_ROLE }}"
      output_location: "rigel-robomaker-logs"
      simulation_duration: 600

      robot_application:
        ecr: "{{ vars.AWS_ECR }}/atom_image:latest"
        command: ["roslaunch", "t2rgb_bringup", "app_launch.launch", "motion_sequence_file:=/home/rigeluser/ros_workspace/src/t2rgb/movement_sequences/movement_sequence.json", "output_folder:=/home/rigeluser/ros_workspace/src/t2rgb/datasets/new_dataset", "overwrite:=true"]
        
        environment:
          - "GAZEBO_MASTER_URI=http://ROBOMAKER_SIM_APP_IP:11345"
          - "ROS_IP=ROBOMAKER_ROBOT_APP_IP"
          - "ROS_MASTER_URI=http://ROBOMAKER_ROBOT_APP_IP:11311"
        
        ports:
          - !!python/tuple [9090, 9090]
        
        tools:
          -
            name: 'terminal'
            command: "{{ vars.robomaker_tool_terminal_cmd }}"
            stream_output_to_cloud_watch: True
            stream_ui: True
          
          -
            name: 'rviz'
            command: "{{ vars.robomaker_tool_rviz_cmd}}"
            stream_output_to_cloud_watch: True
            stream_ui: True
          
          -
            name: 'gzclient'
            command: "{{ vars.robomaker_tool_gazebo_cmd}}"
            stream_output_to_cloud_watch: True
            stream_ui: True

      vpc_config:
        subnets:
          - "subnet-0c31fe89fff4cda00"
          - "subnet-0229c1b42075fddf3"
        security_groups:
          - "sg-06f70b36208dde8bc"
        assign_public_ip: True

```

Thank you once again for your help!

**Comment by MisterOwlPT** [comment] 2023-07-20 09:14
Hi @Kazadhum,

# Regarding your questions:

1 - The major changes to Rigel have been on the engine itself and not really so much on the plugins.
The most relevant changes to the RoboMaker plugin are the following:
- You don't need anymore to run _both_ a robot application and a simulation application;
- The RoboMaker plugin now supports an optional field called _compute_ (I don't know if you'll need it or not).

2 - Yes, that's absolutely correct.

# Regarding your error:

Your Rigelfile is proper!

The error has been thrown by the AWS API and then caught by Rigel.
It seems the request made by Rigel to the API to create the RoboMaker simulation job is invalid due to the **optional** field `dataSources` (`data_sources` on the Rigelfile) not being declared properly.

I suspect there must have been some changes on the AWS side.
By default, if not specified on the Rigelfile, Rigel would set that field to `[]` and all would be fine.
Apparently, you must _now_ either declare a non-empty list or not declare it at all!
I updated the RoboMaker plugin to reflect this behavior and the error disappeared.

Changes were committed to the branch `develop`.
Just `git pull` these changes and you should be good to go.

---

Please let me know if the problem is solved 😃

**Comment by Kazadhum** [comment] 2023-07-20 09:59
Hi @MisterOwlPT! Thank you for the support!

That problem is fixed, but I've ran into another! Using the same Rigelfile:
```

WARNING - Press CTRL-C / CTRL-Z to stop execution
Connecting to providers
Attempting login with ECR '**********************************'

Login Succeeded
Logged in with success to ECR '************************************
Authenticated with AWS RoboMaker.
Found existing robot application 'rigel_robomaker_robot_application'
Traceback (most recent call last):
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/bin/rigel", line 6, in <module>
    sys.exit(main())
  File "/home/diogo/rigel/rigel/main.py", line 50, in main
    cli()
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/diogo/rigel/rigel/cli/command.py", line 23, in callback
    f(self, *f_args, **f_kwargs)
  File "/home/diogo/rigel/rigel/cli/run.py", line 25, in job
    orchestrator.run_job(job)
  File "/home/diogo/rigel/rigel/orchestrator.py", line 222, in run_job
    self.execute(execution_plan)
  File "/home/diogo/rigel/rigel/orchestrator.py", line 199, in execute
    stage.execute(
  File "/home/diogo/rigel/rigel/executor.py", line 218, in execute
    job.setup()
  File "/home/diogo/rigel/rigel/plugins/aws/robomaker/plugin.py", line 259, in setup
    self.__simulation_job = self.create_simulation_job()
  File "/home/diogo/rigel/rigel/plugins/aws/robomaker/plugin.py", line 194, in create_simulation_job
    simulation_job = self.__robomaker_client.create_simulation_job(**kwargs)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/diogo/.cache/pypoetry/virtualenvs/rigel-qWiewPfQ-py3.8/lib/python3.8/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the CreateSimulationJob operation: Cross-account pass role is not allowed.
```

**Comment by MisterOwlPT** [comment] 2023-07-20 10:16
@Kazadhum,

This is another error thrown by the AWS API: `An error occurred (AccessDeniedException) when calling the CreateSimulationJob operation: Cross-account pass role is not allowed.`

Unfortunately, this is something I can not help you directly with 😞 
You'll have to contact @rarrais since he is the only person who can give you the required AWS account permissions.
I suggest you talk with him ASAP.

**Comment by Kazadhum** [comment] 2023-07-20 10:24
Okok, thank you!

**Comment by MisterOwlPT** [comment] 2023-07-20 15:58
@Kazadhum,

I got a chance to speak with @rarrais about your problem just now.

We think it is solved but we need you to try again.
There's nothing to update on your side.

Let us know if the problem persists

**Comment by Kazadhum** [comment] 2023-07-20 16:03
@MisterOwlPT @rarrais Hello!

Having just retried it, the problem does persist. The error message is the same.

**Comment by MisterOwlPT** [comment] 2023-07-21 10:26
@Kazadhum,

I am here trying to understand what is happening and have some questions.

I noticed that are already some simulation jobs in the AWS Ireland region `eu-west-1` related to Atom.
Did you create these jobs manually using the AWS console (browser)?

**Comment by Kazadhum** [comment] 2023-07-21 10:30
Hello @MisterOwlPT. Yes, those simlations were created manually in the AWS console.

**Comment by MisterOwlPT** [comment] 2023-07-21 15:25
@Kazadhum,

An additional suggestion for debugging... have you ever tried using the [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) itself to interact with RoboMaker?

If not, can you try to use it to create a simulation job with RoboMaker.
The idea is to see if the same error appears.

P.S: send me your Rigelfile nonetheless 😄

**Closed as completed** 2023-07-31 19:31 UTC
